/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace ArtifactRegistry {
  export type ArtifactStruct = {
    id: BytesLike;
    creator: AddressLike;
    createdAt: BigNumberish;
    updatedAt: BigNumberish;
    version: BigNumberish;
    metadataURI: string;
    metadataHash: BytesLike;
    storageURI: string;
    storageHash: BytesLike;
    exists: boolean;
  };

  export type ArtifactStructOutput = [
    id: string,
    creator: string,
    createdAt: bigint,
    updatedAt: bigint,
    version: bigint,
    metadataURI: string,
    metadataHash: string,
    storageURI: string,
    storageHash: string,
    exists: boolean
  ] & {
    id: string;
    creator: string;
    createdAt: bigint;
    updatedAt: bigint;
    version: bigint;
    metadataURI: string;
    metadataHash: string;
    storageURI: string;
    storageHash: string;
    exists: boolean;
  };
}

export interface ArtifactRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "artifactCount"
      | "computeArtifactId"
      | "createArtifact"
      | "getArtifact"
      | "getArtifactIdAt"
      | "getArtifactsByCreator"
      | "nextArtifactNonce"
      | "updateArtifact"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ArtifactCreated" | "ArtifactUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "artifactCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "computeArtifactId",
    values: [AddressLike, BigNumberish, string, BytesLike, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createArtifact",
    values: [string, BytesLike, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getArtifact",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getArtifactIdAt",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getArtifactsByCreator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nextArtifactNonce",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateArtifact",
    values: [BytesLike, string, BytesLike, string, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "artifactCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "computeArtifactId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createArtifact",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getArtifact",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getArtifactIdAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getArtifactsByCreator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextArtifactNonce",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateArtifact",
    data: BytesLike
  ): Result;
}

export namespace ArtifactCreatedEvent {
  export type InputTuple = [
    artifactId: BytesLike,
    creator: AddressLike,
    timestamp: BigNumberish,
    version: BigNumberish,
    metadataURI: string,
    metadataHash: BytesLike,
    storageURI: string,
    storageHash: BytesLike
  ];
  export type OutputTuple = [
    artifactId: string,
    creator: string,
    timestamp: bigint,
    version: bigint,
    metadataURI: string,
    metadataHash: string,
    storageURI: string,
    storageHash: string
  ];
  export interface OutputObject {
    artifactId: string;
    creator: string;
    timestamp: bigint;
    version: bigint;
    metadataURI: string;
    metadataHash: string;
    storageURI: string;
    storageHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ArtifactUpdatedEvent {
  export type InputTuple = [
    artifactId: BytesLike,
    creator: AddressLike,
    timestamp: BigNumberish,
    version: BigNumberish,
    metadataURI: string,
    metadataHash: BytesLike,
    storageURI: string,
    storageHash: BytesLike
  ];
  export type OutputTuple = [
    artifactId: string,
    creator: string,
    timestamp: bigint,
    version: bigint,
    metadataURI: string,
    metadataHash: string,
    storageURI: string,
    storageHash: string
  ];
  export interface OutputObject {
    artifactId: string;
    creator: string;
    timestamp: bigint;
    version: bigint;
    metadataURI: string;
    metadataHash: string;
    storageURI: string;
    storageHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ArtifactRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ArtifactRegistry;
  waitForDeployment(): Promise<this>;

  interface: ArtifactRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  artifactCount: TypedContractMethod<[], [bigint], "view">;

  computeArtifactId: TypedContractMethod<
    [
      creator: AddressLike,
      nonce: BigNumberish,
      metadataURI: string,
      metadataHash: BytesLike,
      storageURI: string,
      storageHash: BytesLike
    ],
    [string],
    "view"
  >;

  createArtifact: TypedContractMethod<
    [
      metadataURI: string,
      metadataHash: BytesLike,
      storageURI: string,
      storageHash: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  getArtifact: TypedContractMethod<
    [artifactId: BytesLike],
    [ArtifactRegistry.ArtifactStructOutput],
    "view"
  >;

  getArtifactIdAt: TypedContractMethod<[index: BigNumberish], [string], "view">;

  getArtifactsByCreator: TypedContractMethod<
    [creator: AddressLike],
    [string[]],
    "view"
  >;

  nextArtifactNonce: TypedContractMethod<[], [bigint], "view">;

  updateArtifact: TypedContractMethod<
    [
      artifactId: BytesLike,
      metadataURI: string,
      metadataHash: BytesLike,
      storageURI: string,
      storageHash: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "artifactCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "computeArtifactId"
  ): TypedContractMethod<
    [
      creator: AddressLike,
      nonce: BigNumberish,
      metadataURI: string,
      metadataHash: BytesLike,
      storageURI: string,
      storageHash: BytesLike
    ],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "createArtifact"
  ): TypedContractMethod<
    [
      metadataURI: string,
      metadataHash: BytesLike,
      storageURI: string,
      storageHash: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getArtifact"
  ): TypedContractMethod<
    [artifactId: BytesLike],
    [ArtifactRegistry.ArtifactStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getArtifactIdAt"
  ): TypedContractMethod<[index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getArtifactsByCreator"
  ): TypedContractMethod<[creator: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "nextArtifactNonce"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "updateArtifact"
  ): TypedContractMethod<
    [
      artifactId: BytesLike,
      metadataURI: string,
      metadataHash: BytesLike,
      storageURI: string,
      storageHash: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  getEvent(
    key: "ArtifactCreated"
  ): TypedContractEvent<
    ArtifactCreatedEvent.InputTuple,
    ArtifactCreatedEvent.OutputTuple,
    ArtifactCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ArtifactUpdated"
  ): TypedContractEvent<
    ArtifactUpdatedEvent.InputTuple,
    ArtifactUpdatedEvent.OutputTuple,
    ArtifactUpdatedEvent.OutputObject
  >;

  filters: {
    "ArtifactCreated(bytes32,address,uint64,uint64,string,bytes32,string,bytes32)": TypedContractEvent<
      ArtifactCreatedEvent.InputTuple,
      ArtifactCreatedEvent.OutputTuple,
      ArtifactCreatedEvent.OutputObject
    >;
    ArtifactCreated: TypedContractEvent<
      ArtifactCreatedEvent.InputTuple,
      ArtifactCreatedEvent.OutputTuple,
      ArtifactCreatedEvent.OutputObject
    >;

    "ArtifactUpdated(bytes32,address,uint64,uint64,string,bytes32,string,bytes32)": TypedContractEvent<
      ArtifactUpdatedEvent.InputTuple,
      ArtifactUpdatedEvent.OutputTuple,
      ArtifactUpdatedEvent.OutputObject
    >;
    ArtifactUpdated: TypedContractEvent<
      ArtifactUpdatedEvent.InputTuple,
      ArtifactUpdatedEvent.OutputTuple,
      ArtifactUpdatedEvent.OutputObject
    >;
  };
}
