/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace DataLoopCore {
  export type CorrectionStruct = {
    id: BigNumberish;
    taskId: BytesLike;
    submitter: AddressLike;
    submittedAt: BigNumberish;
    metadataURI: string;
    metadataHash: BytesLike;
    totalStake: BigNumberish;
    exists: boolean;
  };

  export type CorrectionStructOutput = [
    id: bigint,
    taskId: string,
    submitter: string,
    submittedAt: bigint,
    metadataURI: string,
    metadataHash: string,
    totalStake: bigint,
    exists: boolean
  ] & {
    id: bigint;
    taskId: string;
    submitter: string;
    submittedAt: bigint;
    metadataURI: string;
    metadataHash: string;
    totalStake: bigint;
    exists: boolean;
  };

  export type DatasetVersionStruct = {
    datasetId: BytesLike;
    version: BigNumberish;
    registrar: AddressLike;
    registeredAt: BigNumberish;
    metadataURI: string;
    metadataHash: BytesLike;
    exists: boolean;
  };

  export type DatasetVersionStructOutput = [
    datasetId: string,
    version: bigint,
    registrar: string,
    registeredAt: bigint,
    metadataURI: string,
    metadataHash: string,
    exists: boolean
  ] & {
    datasetId: string;
    version: bigint;
    registrar: string;
    registeredAt: bigint;
    metadataURI: string;
    metadataHash: string;
    exists: boolean;
  };

  export type StakeStruct = {
    id: BigNumberish;
    staker: AddressLike;
    referenceType: BigNumberish;
    taskId: BytesLike;
    correctionId: BigNumberish;
    amount: BigNumberish;
    lockedAt: BigNumberish;
    released: boolean;
  };

  export type StakeStructOutput = [
    id: bigint,
    staker: string,
    referenceType: bigint,
    taskId: string,
    correctionId: bigint,
    amount: bigint,
    lockedAt: bigint,
    released: boolean
  ] & {
    id: bigint;
    staker: string;
    referenceType: bigint;
    taskId: string;
    correctionId: bigint;
    amount: bigint;
    lockedAt: bigint;
    released: boolean;
  };

  export type TaskStruct = {
    id: BytesLike;
    creator: AddressLike;
    createdAt: BigNumberish;
    metadataURI: string;
    metadataHash: BytesLike;
    totalStake: BigNumberish;
    exists: boolean;
  };

  export type TaskStructOutput = [
    id: string,
    creator: string,
    createdAt: bigint,
    metadataURI: string,
    metadataHash: string,
    totalStake: bigint,
    exists: boolean
  ] & {
    id: string;
    creator: string;
    createdAt: bigint;
    metadataURI: string;
    metadataHash: string;
    totalStake: bigint;
    exists: boolean;
  };
}

export interface DataLoopCoreInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createTask"
      | "depositStakeForCorrection"
      | "depositStakeForTask"
      | "getCorrection"
      | "getCorrectionsForTask"
      | "getDatasetVersion"
      | "getStake"
      | "getTask"
      | "latestDatasetVersion"
      | "minimumStakeLockPeriod"
      | "nextCorrectionId"
      | "nextStakeId"
      | "owner"
      | "registerDatasetVersion"
      | "releaseStake"
      | "submitCorrection"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CorrectionSubmitted"
      | "DatasetRegistered"
      | "StakeDeposited"
      | "StakeReleased"
      | "TaskCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createTask",
    values: [BytesLike, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "depositStakeForCorrection",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositStakeForTask",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCorrection",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCorrectionsForTask",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDatasetVersion",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getStake",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getTask", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "latestDatasetVersion",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "minimumStakeLockPeriod",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextCorrectionId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextStakeId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerDatasetVersion",
    values: [BytesLike, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "releaseStake",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitCorrection",
    values: [BytesLike, string, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "createTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositStakeForCorrection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositStakeForTask",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCorrection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCorrectionsForTask",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDatasetVersion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getStake", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "latestDatasetVersion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minimumStakeLockPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextCorrectionId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextStakeId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerDatasetVersion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releaseStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitCorrection",
    data: BytesLike
  ): Result;
}

export namespace CorrectionSubmittedEvent {
  export type InputTuple = [
    correctionId: BigNumberish,
    taskId: BytesLike,
    submitter: AddressLike,
    timestamp: BigNumberish,
    metadataURI: string,
    metadataHash: BytesLike
  ];
  export type OutputTuple = [
    correctionId: bigint,
    taskId: string,
    submitter: string,
    timestamp: bigint,
    metadataURI: string,
    metadataHash: string
  ];
  export interface OutputObject {
    correctionId: bigint;
    taskId: string;
    submitter: string;
    timestamp: bigint;
    metadataURI: string;
    metadataHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DatasetRegisteredEvent {
  export type InputTuple = [
    datasetId: BytesLike,
    version: BigNumberish,
    registrar: AddressLike,
    timestamp: BigNumberish,
    metadataURI: string,
    metadataHash: BytesLike
  ];
  export type OutputTuple = [
    datasetId: string,
    version: bigint,
    registrar: string,
    timestamp: bigint,
    metadataURI: string,
    metadataHash: string
  ];
  export interface OutputObject {
    datasetId: string;
    version: bigint;
    registrar: string;
    timestamp: bigint;
    metadataURI: string;
    metadataHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakeDepositedEvent {
  export type InputTuple = [
    stakeId: BigNumberish,
    staker: AddressLike,
    referenceType: BigNumberish,
    taskId: BytesLike,
    correctionId: BigNumberish,
    amount: BigNumberish,
    lockedAt: BigNumberish
  ];
  export type OutputTuple = [
    stakeId: bigint,
    staker: string,
    referenceType: bigint,
    taskId: string,
    correctionId: bigint,
    amount: bigint,
    lockedAt: bigint
  ];
  export interface OutputObject {
    stakeId: bigint;
    staker: string;
    referenceType: bigint;
    taskId: string;
    correctionId: bigint;
    amount: bigint;
    lockedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakeReleasedEvent {
  export type InputTuple = [
    stakeId: BigNumberish,
    staker: AddressLike,
    amount: BigNumberish,
    releasedBy: AddressLike
  ];
  export type OutputTuple = [
    stakeId: bigint,
    staker: string,
    amount: bigint,
    releasedBy: string
  ];
  export interface OutputObject {
    stakeId: bigint;
    staker: string;
    amount: bigint;
    releasedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskCreatedEvent {
  export type InputTuple = [
    taskId: BytesLike,
    creator: AddressLike,
    timestamp: BigNumberish,
    metadataURI: string,
    metadataHash: BytesLike
  ];
  export type OutputTuple = [
    taskId: string,
    creator: string,
    timestamp: bigint,
    metadataURI: string,
    metadataHash: string
  ];
  export interface OutputObject {
    taskId: string;
    creator: string;
    timestamp: bigint;
    metadataURI: string;
    metadataHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DataLoopCore extends BaseContract {
  connect(runner?: ContractRunner | null): DataLoopCore;
  waitForDeployment(): Promise<this>;

  interface: DataLoopCoreInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createTask: TypedContractMethod<
    [taskId: BytesLike, metadataURI: string, metadataHash: BytesLike],
    [bigint],
    "payable"
  >;

  depositStakeForCorrection: TypedContractMethod<
    [correctionId: BigNumberish],
    [bigint],
    "payable"
  >;

  depositStakeForTask: TypedContractMethod<
    [taskId: BytesLike],
    [bigint],
    "payable"
  >;

  getCorrection: TypedContractMethod<
    [correctionId: BigNumberish],
    [DataLoopCore.CorrectionStructOutput],
    "view"
  >;

  getCorrectionsForTask: TypedContractMethod<
    [taskId: BytesLike],
    [bigint[]],
    "view"
  >;

  getDatasetVersion: TypedContractMethod<
    [datasetId: BytesLike, version: BigNumberish],
    [DataLoopCore.DatasetVersionStructOutput],
    "view"
  >;

  getStake: TypedContractMethod<
    [stakeId: BigNumberish],
    [DataLoopCore.StakeStructOutput],
    "view"
  >;

  getTask: TypedContractMethod<
    [taskId: BytesLike],
    [DataLoopCore.TaskStructOutput],
    "view"
  >;

  latestDatasetVersion: TypedContractMethod<
    [arg0: BytesLike],
    [bigint],
    "view"
  >;

  minimumStakeLockPeriod: TypedContractMethod<[], [bigint], "view">;

  nextCorrectionId: TypedContractMethod<[], [bigint], "view">;

  nextStakeId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  registerDatasetVersion: TypedContractMethod<
    [datasetId: BytesLike, metadataURI: string, metadataHash: BytesLike],
    [bigint],
    "nonpayable"
  >;

  releaseStake: TypedContractMethod<
    [stakeId: BigNumberish],
    [void],
    "nonpayable"
  >;

  submitCorrection: TypedContractMethod<
    [taskId: BytesLike, metadataURI: string, metadataHash: BytesLike],
    [[bigint, bigint] & { correctionId: bigint; stakeId: bigint }],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createTask"
  ): TypedContractMethod<
    [taskId: BytesLike, metadataURI: string, metadataHash: BytesLike],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "depositStakeForCorrection"
  ): TypedContractMethod<[correctionId: BigNumberish], [bigint], "payable">;
  getFunction(
    nameOrSignature: "depositStakeForTask"
  ): TypedContractMethod<[taskId: BytesLike], [bigint], "payable">;
  getFunction(
    nameOrSignature: "getCorrection"
  ): TypedContractMethod<
    [correctionId: BigNumberish],
    [DataLoopCore.CorrectionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCorrectionsForTask"
  ): TypedContractMethod<[taskId: BytesLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getDatasetVersion"
  ): TypedContractMethod<
    [datasetId: BytesLike, version: BigNumberish],
    [DataLoopCore.DatasetVersionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getStake"
  ): TypedContractMethod<
    [stakeId: BigNumberish],
    [DataLoopCore.StakeStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTask"
  ): TypedContractMethod<
    [taskId: BytesLike],
    [DataLoopCore.TaskStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "latestDatasetVersion"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "minimumStakeLockPeriod"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextCorrectionId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextStakeId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerDatasetVersion"
  ): TypedContractMethod<
    [datasetId: BytesLike, metadataURI: string, metadataHash: BytesLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "releaseStake"
  ): TypedContractMethod<[stakeId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitCorrection"
  ): TypedContractMethod<
    [taskId: BytesLike, metadataURI: string, metadataHash: BytesLike],
    [[bigint, bigint] & { correctionId: bigint; stakeId: bigint }],
    "payable"
  >;

  getEvent(
    key: "CorrectionSubmitted"
  ): TypedContractEvent<
    CorrectionSubmittedEvent.InputTuple,
    CorrectionSubmittedEvent.OutputTuple,
    CorrectionSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "DatasetRegistered"
  ): TypedContractEvent<
    DatasetRegisteredEvent.InputTuple,
    DatasetRegisteredEvent.OutputTuple,
    DatasetRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "StakeDeposited"
  ): TypedContractEvent<
    StakeDepositedEvent.InputTuple,
    StakeDepositedEvent.OutputTuple,
    StakeDepositedEvent.OutputObject
  >;
  getEvent(
    key: "StakeReleased"
  ): TypedContractEvent<
    StakeReleasedEvent.InputTuple,
    StakeReleasedEvent.OutputTuple,
    StakeReleasedEvent.OutputObject
  >;
  getEvent(
    key: "TaskCreated"
  ): TypedContractEvent<
    TaskCreatedEvent.InputTuple,
    TaskCreatedEvent.OutputTuple,
    TaskCreatedEvent.OutputObject
  >;

  filters: {
    "CorrectionSubmitted(uint256,bytes32,address,uint64,string,bytes32)": TypedContractEvent<
      CorrectionSubmittedEvent.InputTuple,
      CorrectionSubmittedEvent.OutputTuple,
      CorrectionSubmittedEvent.OutputObject
    >;
    CorrectionSubmitted: TypedContractEvent<
      CorrectionSubmittedEvent.InputTuple,
      CorrectionSubmittedEvent.OutputTuple,
      CorrectionSubmittedEvent.OutputObject
    >;

    "DatasetRegistered(bytes32,uint256,address,uint64,string,bytes32)": TypedContractEvent<
      DatasetRegisteredEvent.InputTuple,
      DatasetRegisteredEvent.OutputTuple,
      DatasetRegisteredEvent.OutputObject
    >;
    DatasetRegistered: TypedContractEvent<
      DatasetRegisteredEvent.InputTuple,
      DatasetRegisteredEvent.OutputTuple,
      DatasetRegisteredEvent.OutputObject
    >;

    "StakeDeposited(uint256,address,uint8,bytes32,uint256,uint256,uint64)": TypedContractEvent<
      StakeDepositedEvent.InputTuple,
      StakeDepositedEvent.OutputTuple,
      StakeDepositedEvent.OutputObject
    >;
    StakeDeposited: TypedContractEvent<
      StakeDepositedEvent.InputTuple,
      StakeDepositedEvent.OutputTuple,
      StakeDepositedEvent.OutputObject
    >;

    "StakeReleased(uint256,address,uint256,address)": TypedContractEvent<
      StakeReleasedEvent.InputTuple,
      StakeReleasedEvent.OutputTuple,
      StakeReleasedEvent.OutputObject
    >;
    StakeReleased: TypedContractEvent<
      StakeReleasedEvent.InputTuple,
      StakeReleasedEvent.OutputTuple,
      StakeReleasedEvent.OutputObject
    >;

    "TaskCreated(bytes32,address,uint64,string,bytes32)": TypedContractEvent<
      TaskCreatedEvent.InputTuple,
      TaskCreatedEvent.OutputTuple,
      TaskCreatedEvent.OutputObject
    >;
    TaskCreated: TypedContractEvent<
      TaskCreatedEvent.InputTuple,
      TaskCreatedEvent.OutputTuple,
      TaskCreatedEvent.OutputObject
    >;
  };
}
